(function (root, factory) {
    if (typeof module === 'object' && module.exports) module.exports = factory();
    else root.ANNOTATION_DATA = factory();
}(typeof window !== 'undefined' ? window : globalThis, function () {
    'use strict';

    const javaApi = 'https://docs.oracle.com/en/java/javase/17/docs/api/java.base/';
    const springApi = 'https://docs.spring.io/spring-framework/docs/6.2.x/javadoc-api/';
    const bootApi = 'https://docs.spring.io/spring-boot/3.5/api/java/';
    const mybatisApi = 'https://mybatis.org/mybatis-3/apidocs/org/apache/ibatis/annotations/';
    const validationApi = 'https://jakarta.ee/specifications/bean-validation/3.0/apidocs/jakarta/validation/';
    const lombokApi = 'https://projectlombok.org/api/';
    const springSource = fullName => springApi + fullName.replace(/\./g, '/') + '.html';
    const bootSource = fullName => bootApi + fullName.replace(/\./g, '/') + '.html';

    // Each entry is independent; helper keeps the browser and Node catalog identical.
    function annotation(name, category, packageName, summary, targets, attributes, example,
        pitfalls, question, answer, url, frequency = 'high', phase = '运行期') {
        return {
            id: name.slice(1).toLowerCase(), name, category, summary, packageName,
            targets, phase, frequency, attributes, example, pitfalls,
            interview: { question, answer }, sources: [{ label: name + ' 官方文档', url }]
        };
    }

    const categories = [
        { id: 'meta', name: '元注解', description: '定义注解的使用位置、保留策略与继承规则。' },
        { id: 'jdk', name: 'JDK 内置', description: '让编译器检查重写、弃用与泛型等代码约定。' },
        { id: 'container', name: 'Spring 容器', description: '注册 Bean、扫描组件、注入依赖和配置值。' },
        { id: 'boot', name: 'Spring Boot 配置', description: '启动组合、配置绑定与条件装配。' },
        { id: 'web', name: 'Web 接口', description: '声明路由、绑定参数、输出响应和处理异常。' },
        { id: 'validation', name: '参数校验', description: '区分校验触发、级联校验与具体约束。' },
        { id: 'persistence', name: 'MyBatis', description: '注册 Mapper、绑定 SQL 参数与执行数据库操作。' },
        { id: 'lombok', name: 'Lombok', description: '在编译期生成访问器、构造器、Builder 和日志字段。' },
        { id: 'advanced', name: '事务与运行机制', description: '通过代理实现事务、异步与缓存，并配置定时任务。' }
    ];

    const annotations = [
        annotation('@Target', 'meta', 'java.lang.annotation.Target',
            '限定自定义注解可放在类、方法、字段、参数或类型使用等位置。', ['注解声明'],
            ['value：ElementType 数组，如 TYPE、METHOD、FIELD、PARAMETER、TYPE_USE。'],
            '@Target({ElementType.TYPE, ElementType.METHOD})\npublic @interface Audit {}',
            ['声明位置与 TYPE_USE 是不同概念；未声明 @Target 不代表可用于所有类型使用位置。'],
            '@Target 和 @Retention 分别控制什么？', '前者控制能写在哪里，后者控制注解信息保留到哪个阶段。',
            javaApi + 'java/lang/annotation/Target.html', 'high', '编译期'),
        annotation('@Retention', 'meta', 'java.lang.annotation.Retention',
            '声明注解信息保留到源码、class 文件还是运行时。', ['注解声明'],
            ['value：RetentionPolicy.SOURCE、CLASS 或 RUNTIME；不声明时默认 CLASS。'],
            '@Retention(RetentionPolicy.RUNTIME)\npublic @interface Audit {}',
            ['只有 RUNTIME 保留策略才能通过常规运行时反射读取；RUNTIME 本身不会执行业务逻辑。'],
            '自定义注解不写 @Retention 会怎样？', '默认采用 CLASS，写入 class 文件，但通常不能通过运行时反射读取。',
            javaApi + 'java/lang/annotation/Retention.html', 'high', '编译期'),
        annotation('@Documented', 'meta', 'java.lang.annotation.Documented',
            '让使用该注解的信息默认出现在生成的 API 文档中。', ['注解声明'], ['无属性。'],
            '@Documented\npublic @interface PublicApi {}',
            ['它影响文档呈现，不会启用运行时行为，也不改变保留策略。'],
            '@Documented 是否能让注解被反射读取？', '不能。反射可见性由 @Retention(RUNTIME) 决定。',
            javaApi + 'java/lang/annotation/Documented.html', 'normal', '文档生成期'),
        annotation('@Inherited', 'meta', 'java.lang.annotation.Inherited',
            '通过反射查询类上的指定注解时，允许沿父类链寻找该注解。', ['注解声明'], ['无属性。'],
            '@Inherited\n@Retention(RetentionPolicy.RUNTIME)\n@interface Role {}\n@Role class Parent {}\nclass Child extends Parent {}',
            ['只影响类的父类链；不继承接口上的注解，也不让方法或字段注解自动继承。'],
            '实现带注解的接口会继承这个注解吗？', 'Java 的 @Inherited 不支持接口链；框架可以额外实现自己的注解查找规则。',
            javaApi + 'java/lang/annotation/Inherited.html', 'normal'),
        annotation('@Repeatable', 'meta', 'java.lang.annotation.Repeatable',
            '允许在同一元素上重复书写一种注解，并指定承载重复项的容器注解。', ['注解声明'],
            ['value：容器注解类型；容器的 value() 返回被重复注解的数组。'],
            '@Repeatable(Tags.class)\n@interface Tag { String value(); }\n@interface Tags { Tag[] value(); }\n@Tag("java") @Tag("spring") class Topic {}',
            ['容器注解的保留策略、目标范围等必须符合语言规范；编译期检查重复使用并生成承载重复项的容器注解，运行期能否读取取决于保留策略，常用 getAnnotationsByType。'],
            '重复注解为什么还要容器？', '容器承载多个注解实例，反射 API 可以展开并返回这些实例。',
            javaApi + 'java/lang/annotation/Repeatable.html', 'normal', '编译期检查与容器生成'),

        annotation('@Override', 'jdk', 'java.lang.Override',
            '要求编译器检查方法确实重写父类型方法或实现接口方法。', ['方法'], ['无属性。'],
            'class Job implements Runnable {\n    @Override public void run() { System.out.println("run"); }\n}',
            ['拼错方法名或参数类型会导致编译失败；它不能用于静态方法隐藏。'],
            '不写 @Override 还能重写吗？', '可以。重写由方法签名决定，注解提供额外编译检查。',
            javaApi + 'java/lang/Override.html', 'high', '编译期'),
        annotation('@Deprecated', 'jdk', 'java.lang.Deprecated',
            '标记不推荐继续使用的 API，并可说明弃用版本和计划移除意图。', ['类', '方法', '字段', '构造器', '模块等声明'],
            ['since：开始弃用的版本。', 'forRemoval：是否计划未来移除，默认 false。'],
            '/** @deprecated 请改用 findById。 */\n@Deprecated(since = "2.0", forRemoval = false)\npublic User getUser(long id) { return findById(id); }',
            ['弃用不等于立即删除；注解和 Javadoc 的 @deprecated 标签应说明推荐替代方案。', '主要用途是编译期警告与文档标记；其元数据按 RUNTIME 保留，也可在运行期反射读取，这与主要处理阶段是不同概念。'],
            '@Deprecated 和 @deprecated 有何区别？', '前者是可被编译器识别的注解，后者是文档标签，用于说明理由和替代方案。',
            javaApi + 'java/lang/Deprecated.html', 'high', '编译期警告与文档生成期'),
        annotation('@SuppressWarnings', 'jdk', 'java.lang.SuppressWarnings',
            '抑制指定范围内的编译器警告。', ['类', '方法', '字段', '参数', '局部变量等声明'],
            ['value：警告名称数组，常见 unchecked、deprecation。'],
            '@SuppressWarnings("unchecked")\nList<String> names = (List<String>) legacyResult;',
            ['警告消失不代表类型转换安全；范围尽量小，不宜无差别使用 all。'],
            '为什么不建议类级别大范围抑制 unchecked？', '它会掩盖新引入的不安全转换，应在已核验的最小位置抑制。',
            javaApi + 'java/lang/SuppressWarnings.html', 'normal', '编译期'),
        annotation('@SafeVarargs', 'jdk', 'java.lang.SafeVarargs',
            '声明泛型可变参数方法实现没有对参数执行可能造成堆污染的操作。', ['构造器', 'static、final 或 private 的可变参数方法'],
            ['无属性。'],
            '@SafeVarargs\nstatic <T> List<T> copy(T... values) {\n    List<T> result = new ArrayList<>();\n    for (T value : values) result.add(value);\n    return result;\n}',
            ['它是程序员的安全承诺，不会自动验证方法安全；普通可重写实例方法不能标注。'],
            '@SafeVarargs 会消除堆污染吗？', '不会。它抑制相关警告，开发者仍要确保不进行不安全数组写入或泄露。',
            javaApi + 'java/lang/SafeVarargs.html', 'normal', '编译期'),

        annotation('@Component', 'container', 'org.springframework.stereotype.Component',
            '将普通类标记为组件扫描候选，扫描到后由容器管理。', ['类'], ['value：建议的 Bean 名称。'],
            '@Component\npublic class IdGenerator {\n    public String next() { return UUID.randomUUID().toString(); }\n}',
            ['类必须位于扫描范围内或显式注册；普通 new 创建的对象不会自动经过 Spring 注入。'],
            '@Component 和 @Bean 选哪个？', '自有类适合组件扫描；第三方对象或需要显式组装的对象常通过 @Bean 注册。',
            springSource('org.springframework.stereotype.Component')),
        annotation('@Service', 'container', 'org.springframework.stereotype.Service',
            '标记业务服务层组件，是 @Component 的语义化变体。', ['类'], ['value：Bean 名称。'],
            '@Service\npublic class PriceService {\n    public BigDecimal price() { return BigDecimal.TEN; }\n}',
            ['@Service 本身不提供事务、异步或权限控制，需要对应机制和注解。'],
            '@Service 比 @Component 多了哪些业务能力？', '主要表达服务层角色；事务等增强由独立基础设施提供。',
            springSource('org.springframework.stereotype.Service')),
        annotation('@Repository', 'container', 'org.springframework.stereotype.Repository',
            '标记持久化层组件，并可配合异常转换处理器把底层异常转换为 Spring 数据访问异常。', ['类'], ['value：Bean 名称。'],
            '@Repository\npublic class UserDao {\n    // 通过注入的 JdbcTemplate 等访问数据库。\n}',
            ['异常转换需要相应后处理器；它不会自动生成 MyBatis Mapper SQL。'],
            '@Repository 与 @Mapper 是否相同？', '前者标记 Spring 持久化组件，后者标记 MyBatis 映射接口，实际处理机制不同。',
            springSource('org.springframework.stereotype.Repository')),
        annotation('@Configuration', 'container', 'org.springframework.context.annotation.Configuration',
            '声明提供 Bean 定义的配置类，默认代理其 @Bean 方法以支持容器内对象复用。', ['类'],
            ['proxyBeanMethods：默认 true；false 时 @Bean 方法间直接调用按普通 Java 调用处理。', 'value：配置类 Bean 名称。'],
            '@Configuration(proxyBeanMethods = false)\npublic class ClockConfig {\n    @Bean Clock clock() { return Clock.systemUTC(); }\n}',
            ['proxyBeanMethods=true 时类和被代理方法不能是 final；false 时依赖推荐通过 @Bean 参数注入。'],
            'proxyBeanMethods=false 会取消 Bean 注册吗？', '不会。它取消配置类的方法拦截，容器仍会注册各 @Bean 方法。',
            springSource('org.springframework.context.annotation.Configuration')),
        annotation('@Bean', 'container', 'org.springframework.context.annotation.Bean',
            '将工厂方法返回的对象注册为 Spring Bean，常用于第三方类型或显式对象组装。', ['方法', '注解声明'],
            ['name/value：Bean 名称和别名，默认方法名。', 'initMethod、destroyMethod：生命周期回调方法。'],
            '@Configuration\npublic class ClockConfig {\n    @Bean("utcClock") Clock clock() { return Clock.systemUTC(); }\n}',
            ['在未受容器管理的对象上写 @Bean 不会生效；不能把一次普通方法调用等同于容器查找。'],
            '@Bean 方法的参数从哪里来？', 'Spring 会解析参数所需的依赖并从容器注入，类似构造器注入。',
            springSource('org.springframework.context.annotation.Bean')),
        annotation('@ComponentScan', 'container', 'org.springframework.context.annotation.ComponentScan',
            '指定 Spring 查找组件的包范围与筛选规则。', ['类'],
            ['basePackages/value：扫描包名。', 'basePackageClasses：用标记类指定包，避免字符串拼错。', 'includeFilters、excludeFilters：筛选规则。'],
            '@Configuration\n@ComponentScan(basePackages = "com.example.service")\npublic class AppConfig {}',
            ['默认从该配置类所在包扫描；普通组件扫描不能替代 MyBatis 的 Mapper 接口扫描。'],
            '为什么写了 @Service 仍提示找不到 Bean？', '先检查扫描范围、条件装配和配置类是否被容器加载。',
            springSource('org.springframework.context.annotation.ComponentScan')),
        annotation('@Autowired', 'container', 'org.springframework.beans.factory.annotation.Autowired',
            '通过 Spring 容器解析并注入依赖，支持构造器、字段和方法。', ['构造器', '字段', '方法', '参数', '注解声明'],
            ['required：默认 true；false 表示非必需，具体行为取决于注入位置。'],
            '@Service\npublic class UserService {\n    private final UserRepository users;\n    @Autowired\n    public UserService(UserRepository users) { this.users = users; }\n}',
            ['同类型有多个候选时需要明确选择；只有一个构造器时通常可省略 @Autowired。'],
            '@Autowired 是只按类型还是只按名字注入？', '先按类型筛选，再结合限定符、优先级等规则解析；名字可能是候选匹配的一部分。',
            springSource('org.springframework.beans.factory.annotation.Autowired')),
        annotation('@Qualifier', 'container', 'org.springframework.beans.factory.annotation.Qualifier',
            '在符合类型的 Bean 中进一步限定注入候选。', ['字段', '参数', '方法', '类', '注解声明'],
            ['value：限定符值，可用于匹配 Bean 名称或显式限定标记。'],
            '@Service\npublic class ReportService {\n    private final Clock clock;\n    public ReportService(@Qualifier("utcClock") Clock clock) { this.clock = clock; }\n}',
            ['限定符是在类型候选中筛选，不是完全无视类型的字符串查找；值必须与候选匹配。'],
            '@Qualifier 和 @Primary 的区别？', '前者由注入点明确限定候选，后者给 Bean 设置默认优先级。',
            springSource('org.springframework.beans.factory.annotation.Qualifier')),
        annotation('@Primary', 'container', 'org.springframework.context.annotation.Primary',
            '同类型多个 Bean 存在时，为单值注入指定优先候选。', ['类', '方法'], ['无属性。'],
            '@Configuration\npublic class ClockConfig {\n    @Bean @Primary Clock mainClock() { return Clock.systemUTC(); }\n    @Bean Clock localClock() { return Clock.systemDefaultZone(); }\n}',
            ['多个候选都为 Primary 仍可能冲突；注入 List 等集合时不会只留下 Primary Bean。'],
            '@Primary 会让其他同类型 Bean 不注册吗？', '不会，只影响单值依赖的候选选择。',
            springSource('org.springframework.context.annotation.Primary')),
        annotation('@Resource', 'container', 'jakarta.annotation.Resource',
            'Jakarta 资源注入注解；在 Spring 中常用于按名称注入依赖。', ['字段', '方法', '类'],
            ['name：资源名称。', 'type：资源类型。', 'lookup：标准资源查找名称，具体支持看容器。'],
            '@Service\npublic class ReportService {\n    @Resource(name = "utcClock")\n    private Clock clock;\n}',
            ['Spring 6 / Boot 3 使用 jakarta.annotation.Resource；Boot 2 常见 javax.annotation.Resource。', '未指定 name 的 Spring 注入通常先按字段或属性名匹配，找不到时可退回类型解析；不支持构造器参数注入。'],
            '@Resource 与 @Autowired 有什么区别？', '前者来自 Jakarta 规范，在 Spring 中常按名称解析；后者来自 Spring，支持构造器等类型驱动注入。',
            'https://jakarta.ee/specifications/annotations/2.1/apidocs/jakarta.annotation/jakarta/annotation/resource'),
        annotation('@Value', 'container', 'org.springframework.beans.factory.annotation.Value',
            '注入单个配置值或 Spring 表达式结果。', ['字段', '方法', '参数', '注解声明'],
            ['value：${配置键:默认值} 或 #{SpEL 表达式}。'],
            '@Component\npublic class PageConfig {\n    @Value("${app.page-size:20}")\n    private int pageSize;\n}',
            ['需要对象由 Spring 管理并处理占位符；一组结构化配置通常更适合 @ConfigurationProperties。'],
            '${...} 与 #{...} 有何区别？', '${...} 查找配置属性，#{...} 计算 SpEL 表达式。',
            'https://docs.spring.io/spring-framework/docs/6.2.0/javadoc-api/org/springframework/beans/factory/annotation/Value.html'),

        annotation('@SpringBootApplication', 'boot', 'org.springframework.boot.autoconfigure.SpringBootApplication',
            '组合应用配置、自动配置和组件扫描，是常见 Spring Boot 启动类入口注解。', ['类'],
            ['scanBasePackages：组件扫描范围。', 'exclude：排除指定自动配置。', 'proxyBeanMethods：配置方法代理开关。'],
            'package com.example;\n@SpringBootApplication\npublic class Application {\n    public static void main(String[] args) { SpringApplication.run(Application.class, args); }\n}',
            ['通常放在业务包的上层；scanBasePackages 只调整组件扫描，不直接调整 JPA 实体或 Mapper 的专用扫描。'],
            '@SpringBootApplication 的三个核心组合是什么？', '@SpringBootConfiguration、@EnableAutoConfiguration 和 @ComponentScan。',
            bootSource('org.springframework.boot.autoconfigure.SpringBootApplication')),
        annotation('@EnableAutoConfiguration', 'boot', 'org.springframework.boot.autoconfigure.EnableAutoConfiguration',
            '启用根据类路径、已有 Bean 和配置条件选择的 Spring Boot 自动配置。', ['类'],
            ['exclude：排除自动配置类型。', 'excludeName：按全限定名排除。'],
            '@Configuration\n@EnableAutoConfiguration\npublic class ApplicationConfig {}',
            ['@SpringBootApplication 已包含它；自动配置需要条件成立，不是把所有库中的类都注册成 Bean。'],
            '自动配置和组件扫描有何区别？', '自动配置导入框架提供的条件配置；组件扫描查找指定包中的组件类。',
            bootSource('org.springframework.boot.autoconfigure.EnableAutoConfiguration')),
        annotation('@SpringBootConfiguration', 'boot', 'org.springframework.boot.SpringBootConfiguration',
            '标记 Spring Boot 应用主配置，方便测试等机制自动定位应用配置。', ['类'],
            ['proxyBeanMethods：是否代理 @Bean 方法，默认 true。'],
            '@SpringBootConfiguration\npublic class ApplicationConfig {\n    @Bean Clock clock() { return Clock.systemUTC(); }\n}',
            ['一个应用通常只设置一个主配置；它本身没有包含组件扫描和自动配置。'],
            '只写 @SpringBootConfiguration 等同于 @SpringBootApplication 吗？', '不等同。它提供配置类标记，后者还组合自动配置和扫描。',
            bootSource('org.springframework.boot.SpringBootConfiguration'), 'normal'),
        annotation('@ConfigurationProperties', 'boot', 'org.springframework.boot.context.properties.ConfigurationProperties',
            '把同一前缀下的外部配置绑定成有类型的配置对象。', ['类', '方法'],
            ['prefix/value：配置前缀。', 'ignoreUnknownFields：默认 true。', 'ignoreInvalidFields：默认 false。'],
            '// 启动类添加 @ConfigurationPropertiesScan。\n@ConfigurationProperties(prefix = "app.mail")\npublic record MailProperties(String host, int port) {}',
            ['需要注册配置类型；此示例按 Boot 3 构造器绑定，应使用配置扫描或 @EnableConfigurationProperties，普通 @Component / @Bean 创建方式不采用这种构造器绑定。', '不会像 @Value 一样计算 SpEL；约束校验可配合 @Validated 与校验实现。'],
            '为什么结构化配置适合 @ConfigurationProperties？', '它支持类型转换、分组管理和配置绑定，减少零散字符串键。',
            bootSource('org.springframework.boot.context.properties.ConfigurationProperties')),
        annotation('@ConfigurationPropertiesScan', 'boot', 'org.springframework.boot.context.properties.ConfigurationPropertiesScan',
            '扫描并注册带 @ConfigurationProperties 的配置类型。', ['类'],
            ['basePackages/value：扫描包。', 'basePackageClasses：使用标记类指定扫描包。'],
            '@SpringBootApplication\n@ConfigurationPropertiesScan("com.example.config")\npublic class Application {}',
            ['配置类必须在扫描范围；该扫描不会把直接或间接带 @Component 的类作为配置属性候选。'],
            '配置属性扫描与组件扫描负责同一件事吗？', '不完全相同。前者专门注册配置属性类型，后者注册组件。',
            bootSource('org.springframework.boot.context.properties.ConfigurationPropertiesScan')),
        annotation('@ConditionalOnProperty', 'boot', 'org.springframework.boot.autoconfigure.condition.ConditionalOnProperty',
            '按配置属性的存在及取值决定是否装配配置类或 Bean。', ['类', '方法'],
            ['prefix：配置键前缀。', 'name/value：属性名称。', 'havingValue：要求的值。', 'matchIfMissing：缺失时是否匹配，默认 false。'],
            '@Configuration\npublic class FeatureConfig {\n    @Bean\n    @ConditionalOnProperty(prefix = "app.audit", name = "enabled", havingValue = "true")\n    AuditService auditService() { return new AuditService(); }\n}',
            ['不写 havingValue 时，通常要求属性存在且值不是 false；复杂集合属性不能可靠地用它判断。'],
            '配置键未写时条件一定成立吗？', '默认不成立，需显式 matchIfMissing=true 才在缺失时匹配。',
            bootSource('org.springframework.boot.autoconfigure.condition.ConditionalOnProperty')),
        annotation('@ConditionalOnMissingBean', 'boot', 'org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean',
            '只在容器没有符合条件的 Bean 时提供默认实现，常用于自动配置让用户定制覆盖。', ['类', '方法'],
            ['value：需要缺失的 Bean 类型。', 'name：需要缺失的 Bean 名称。', 'search：父容器搜索策略。'],
            '// 常见于被 Boot 导入的自动配置类。\n@AutoConfiguration\npublic class ClockAutoConfiguration {\n    @Bean\n    @ConditionalOnMissingBean(Clock.class)\n    Clock clock() { return Clock.systemUTC(); }\n}',
            ['条件只能看到已处理的 Bean 定义，装配顺序有影响；通常应在自动配置中使用。'],
            '为什么用户定义 Bean 后默认实现会退让？', '缺失条件不再成立，默认 Bean 就不会注册。',
            bootSource('org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean')),

        annotation('@Controller', 'web', 'org.springframework.stereotype.Controller',
            '标记 Web 控制器组件，配合映射注解处理请求，可返回视图。', ['类'], ['value：Bean 名称。'],
            '@Controller\npublic class HomeController {\n    @GetMapping("/home")\n    public String home() { return "home"; }\n}',
            ['返回字符串常作为视图名解析；若要直接写响应体需 @ResponseBody 或 ResponseEntity 等。'],
            '@Controller 返回字符串一定是 JSON 吗？', '不是。常见 MVC 视图流程将字符串当作视图名。',
            springSource('org.springframework.stereotype.Controller')),
        annotation('@RestController', 'web', 'org.springframework.web.bind.annotation.RestController',
            '组合 @Controller 与 @ResponseBody，使映射方法默认把返回值写入响应体。', ['类'], ['value：Bean 名称。'],
            '@RestController\npublic class PingController {\n    @GetMapping("/ping")\n    public Map<String, String> ping() { return Map.of("status", "ok"); }\n}',
            ['响应格式取决于消息转换器与内容协商，不是所有返回值都必然序列化成 JSON。'],
            '@RestController 为什么适合 REST 接口？', '它默认采用响应体语义，无需在每个接口方法上重复 @ResponseBody。',
            springSource('org.springframework.web.bind.annotation.RestController')),
        annotation('@RequestMapping', 'web', 'org.springframework.web.bind.annotation.RequestMapping',
            '按路径、HTTP 方法、参数、请求头和媒体类型匹配请求。', ['类', '方法'],
            ['path/value：路径。', 'method：HTTP 方法。', 'consumes、produces：请求和响应媒体类型。', 'params、headers：匹配条件。'],
            '@RestController\n@RequestMapping("/users")\npublic class UserController {\n    @RequestMapping(path = "/count", method = RequestMethod.GET)\n    public int count() { return 3; }\n}',
            ['未指定 method 时并不只匹配 GET；同一元素不应叠加多个映射注解。'],
            '类级映射和方法级映射如何组合？', '类级映射提供公共路径和条件，方法级映射进一步限定具体请求。',
            springSource('org.springframework.web.bind.annotation.RequestMapping')),
        annotation('@GetMapping', 'web', 'org.springframework.web.bind.annotation.GetMapping',
            '为读取接口声明 GET 请求映射，是 @RequestMapping(method=GET) 的组合注解。', ['方法'],
            ['path/value：路径。', 'params、headers、consumes、produces：额外匹配条件。'],
            '@GetMapping("/users/{id}")\npublic User find(@PathVariable("id") long id) { return service.find(id); }',
            ['方法所在类需注册为控制器；不要在同一方法再叠加 @PostMapping 期待多个映射生效。'],
            'GET 接口读取路径变量用什么？', '用 @PathVariable 与模板中的变量名对应。',
            springSource('org.springframework.web.bind.annotation.GetMapping')),
        annotation('@PostMapping', 'web', 'org.springframework.web.bind.annotation.PostMapping',
            '为提交或创建操作声明 POST 请求映射。', ['方法'],
            ['path/value：路径。', 'consumes：限制请求 Content-Type。', 'produces：限制响应媒体类型。'],
            '@PostMapping(path = "/users", consumes = "application/json")\npublic User create(@Valid @RequestBody CreateUserRequest request) {\n    return service.create(request);\n}',
            ['POST 不等于自动读取 JSON；需 @RequestBody、消息转换器及正确 Content-Type。'],
            '@PostMapping 会自动执行字段校验吗？', '不会。需校验注解和校验基础设施，并在请求参数上触发校验。',
            springSource('org.springframework.web.bind.annotation.PostMapping')),
        annotation('@RequestParam', 'web', 'org.springframework.web.bind.annotation.RequestParam',
            '把查询参数或 Spring MVC 表单参数绑定到方法参数。', ['参数'],
            ['name/value：参数名。', 'required：默认 true。', 'defaultValue：默认值，同时使参数不再必需。'],
            '@GetMapping("/users")\npublic List<User> list(@RequestParam(name = "page", defaultValue = "1") int page) {\n    return service.list(page);\n}',
            ['不要用它读取任意 JSON 请求体；可缺失的参数要选包装类型、Optional 或默认值。'],
            '@RequestParam 与 @RequestBody 如何选择？', '查询或表单参数用前者，按消息转换器读取整个请求体用后者。',
            springSource('org.springframework.web.bind.annotation.RequestParam')),
        annotation('@PathVariable', 'web', 'org.springframework.web.bind.annotation.PathVariable',
            '把路由模板中的路径变量绑定到方法参数。', ['参数'],
            ['name/value：模板变量名。', 'required：默认 true。'],
            '@GetMapping("/users/{userId}")\npublic User find(@PathVariable("userId") long id) { return service.find(id); }',
            ['变量名要与路径模板一致；显式写名称可减少对编译参数名称信息的依赖。'],
            '/users/42 和 /users?id=42 分别如何绑定？', '前者使用路径模板及 @PathVariable，后者使用 @RequestParam。',
            springSource('org.springframework.web.bind.annotation.PathVariable')),
        annotation('@RequestBody', 'web', 'org.springframework.web.bind.annotation.RequestBody',
            '通过 HTTP 消息转换器读取请求体并转换成方法参数对象。', ['参数'], ['required：默认 true；是否必须有请求体。'],
            '@PostMapping("/users")\npublic User create(@Valid @RequestBody CreateUserRequest request) {\n    return service.create(request);\n}',
            ['JSON 解析取决于转换器与 Content-Type；对象反序列化成功不表示字段约束已通过。'],
            '为什么 @RequestBody DTO 要再加 @Valid？', '前者负责读取并转换请求体，后者触发 Bean Validation 约束检查。',
            springSource('org.springframework.web.bind.annotation.RequestBody')),
        annotation('@ResponseBody', 'web', 'org.springframework.web.bind.annotation.ResponseBody',
            '让返回值通过消息转换器写入 HTTP 响应体。', ['类', '方法'], ['无属性。'],
            '@Controller\npublic class PingController {\n    @GetMapping("/ping") @ResponseBody\n    public String ping() { return "ok"; }\n}',
            ['不是只支持 JSON；String 可以直接作为文本响应，对象格式取决于转换器和协商。'],
            '@ResponseBody 的作用是序列化还是路由匹配？', '它控制响应体处理；路由由 @RequestMapping 等映射注解决定。',
            springSource('org.springframework.web.bind.annotation.ResponseBody')),
        annotation('@RestControllerAdvice', 'web', 'org.springframework.web.bind.annotation.RestControllerAdvice',
            '为一组控制器提供公共增强，并默认把异常处理等方法的返回值写入响应体。', ['类'],
            ['basePackages：限定包。', 'assignableTypes：限定控制器类型。', 'annotations：限定控制器注解。'],
            '@RestControllerAdvice\npublic class ApiErrors {\n    @ExceptionHandler(IllegalArgumentException.class)\n    public ResponseEntity<Map<String, String>> badInput(IllegalArgumentException ex) {\n        return ResponseEntity.badRequest().body(Map.of("message", "参数错误"));\n    }\n}',
            ['只作用于控制器相关处理流程，不能覆盖任意后台线程异常；需要显式设置合适的 HTTP 状态。'],
            '@RestControllerAdvice 为什么常用于统一异常处理？', '它集中声明多个控制器共享的处理方法，并默认输出响应体。',
            springSource('org.springframework.web.bind.annotation.RestControllerAdvice')),
        annotation('@ExceptionHandler', 'web', 'org.springframework.web.bind.annotation.ExceptionHandler',
            '声明控制器或控制器增强类中处理指定异常的方法。', ['方法'],
            ['value/exception：异常类型数组，exception 是 Spring 6.2 的别名。', 'produces：Spring 6.2 支持响应媒体类型匹配。'],
            '@RestControllerAdvice\npublic class ApiErrors {\n    @ExceptionHandler(IllegalArgumentException.class)\n    public ResponseEntity<String> badInput() {\n        return ResponseEntity.badRequest().body("参数错误");\n    }\n}',
            ['返回错误文字不自动意味着 4xx 或 5xx，使用 ResponseEntity 或 @ResponseStatus 指定状态。'],
            '局部和全局异常处理器如何区分？', '控制器内的方法提供局部处理，Advice 中的方法为匹配控制器提供公共处理。',
            springSource('org.springframework.web.bind.annotation.ExceptionHandler')),

        annotation('@Valid', 'validation', 'jakarta.validation.Valid',
            '标记需要级联验证的对象；在 Spring MVC 请求参数处可触发 DTO 校验。', ['字段', '方法', '构造器', '参数', '类型使用'], ['无属性。'],
            'class OrderRequest {\n    @Valid @NotNull\n    private Address address;\n}\n// 控制器参数：@Valid @RequestBody OrderRequest request',
            ['@Valid 本身不是非空约束，嵌套对象需配合 @NotNull；要有校验实现与触发入口。', 'Boot 3 使用 jakarta.validation.Valid，Boot 2 常见 javax.validation.Valid。'],
            '@Valid 与 @NotNull 能互相替代吗？', '不能。前者级联检查内部约束，后者要求对象非 null。',
            validationApi + 'valid'),
        annotation('@Validated', 'validation', 'org.springframework.validation.annotation.Validated',
            'Spring 的校验提示注解，可指定校验分组，并用于服务层方法校验的代理入口。', ['类', '方法', '参数'],
            ['value：校验分组类型数组；未指定时通常校验 Default 组。'],
            '// 需要 Bean Validation 实现与方法校验处理器；Boot 可自动配置。\n@Service @Validated\npublic class UserService {\n    public void rename(@NotBlank String name) { /* 更新名称 */ }\n}',
            ['服务层代理方法校验需要相应处理器，默认代理模式下自调用不经过代理。', 'Spring 6.1+ 的 MVC 内置方法校验可处理参数约束；要采用它时移除控制器类级 @Validated。'],
            '@Validated 比 @Valid 多解决什么？', '它提供 Spring 校验提示及分组选择；类级标记还可作为方法校验的切入点。',
            springSource('org.springframework.validation.annotation.Validated')),
        annotation('@NotNull', 'validation', 'jakarta.validation.constraints.NotNull',
            '要求值不是 null，适用于任意引用类型。', ['字段', '方法', '参数', '构造器', '注解声明', '类型使用'],
            ['message：校验消息。', 'groups：校验分组。', 'payload：附加元数据。'],
            'class CreateUserRequest {\n    @NotNull(message = "年龄必填")\n    private Integer age;\n}',
            ['空字符串、空集合仍非 null，因此可以通过；基本类型也无法表达 null。'],
            '@NotNull 可以禁止空字符串吗？', '不能，字符串内容要求通常使用 @NotBlank 或 @NotEmpty。',
            validationApi + 'constraints/notnull'),
        annotation('@NotBlank', 'validation', 'jakarta.validation.constraints.NotBlank',
            '要求字符序列非 null，且至少包含一个非空白字符。', ['字段', '方法', '参数', '构造器', '注解声明', '类型使用'],
            ['message：消息。', 'groups：分组。', 'payload：附加元数据。'],
            'class CreateUserRequest {\n    @NotBlank(message = "用户名不能为空白")\n    private String username;\n}',
            ['用于 CharSequence，不能标在 Integer、List 等不支持的类型上；不会自动 trim 或修改字符串。'],
            '@NotBlank 与 @NotEmpty 有何区别？', '对字符串而言，NotBlank 要求存在非空白字符，NotEmpty 只要求长度大于 0。',
            validationApi + 'constraints/notblank'),
        annotation('@NotEmpty', 'validation', 'jakarta.validation.constraints.NotEmpty',
            '要求字符序列、集合、Map 或数组非 null 且长度或大小大于 0。', ['字段', '方法', '参数', '构造器', '注解声明', '类型使用'],
            ['message：消息。', 'groups：分组。', 'payload：附加元数据。'],
            'class BatchRequest {\n    @NotEmpty\n    private List<Long> ids;\n}',
            ['不能确保集合每个元素有效；元素约束可用 List<@NotNull Long>，嵌套对象可用 @Valid。'],
            'List 上 @NotEmpty 能检查里面的 null 吗？', '不能，它检查集合自身是否非空；元素需要独立约束。',
            validationApi + 'constraints/notempty'),
        annotation('@Size', 'validation', 'jakarta.validation.constraints.Size',
            '限制字符序列长度、集合或 Map 大小、数组长度，边界包含在范围内。', ['字段', '方法', '参数', '构造器', '注解声明', '类型使用'],
            ['min：最小长度，默认 0。', 'max：最大长度，默认 Integer.MAX_VALUE。', 'message、groups、payload：通用校验配置。'],
            'class CreateUserRequest {\n    @NotBlank @Size(min = 2, max = 30)\n    private String username;\n}',
            ['null 被视为合法，必填要另加非空约束；@Size 检查长度而非数值大小。'],
            '限制年龄至少 18 应用 @Size 吗？', '不应用。数值边界用 @Min，@Size 用于长度或元素个数。',
            validationApi + 'constraints/size'),
        annotation('@Min', 'validation', 'jakarta.validation.constraints.Min',
            '要求支持的数值类型大于或等于指定整数边界。', ['字段', '方法', '参数', '构造器', '注解声明', '类型使用'],
            ['value：最小值，long 类型。', 'message、groups、payload：通用校验配置。'],
            'class CreateUserRequest {\n    @NotNull @Min(value = 18, message = "年龄至少 18")\n    private Integer age;\n}',
            ['null 被视为合法；规范不要求支持 float、double，金额常用 BigDecimal 配合 @DecimalMin。'],
            '@Min(1) 会拒绝 null 吗？', '不会，必填字段还需 @NotNull。',
            validationApi + 'constraints/min'),
        annotation('@Email', 'validation', 'jakarta.validation.constraints.Email',
            '验证字符序列是否符合校验实现定义的邮箱地址规则。', ['字段', '方法', '参数', '构造器', '注解声明', '类型使用'],
            ['regexp、flags：附加正则约束。', 'message、groups、payload：通用校验配置。'],
            'class CreateUserRequest {\n    @NotBlank @Email\n    private String email;\n}',
            ['null 被视为合法，必填配合 @NotBlank；格式通过不代表邮箱存在或属于该用户。'],
            '通过 @Email 是否表示能收到邮件？', '不是。它验证格式，送达能力与归属需要发送确认邮件等流程。',
            validationApi + 'constraints/email'),

        annotation('@Mapper', 'persistence', 'org.apache.ibatis.annotations.Mapper',
            '标记 MyBatis Mapper 接口，供相应扫描和集成机制识别。', ['Mapper 接口（常用）'], ['无属性。'],
            '@Mapper\npublic interface UserMapper {\n    @Select("SELECT id, name FROM users WHERE id = #{id}")\n    User find(@Param("id") long id);\n}',
            ['注解自身不会创建数据库连接；需要 MyBatis 配置与 Mapper 注册，Spring Boot starter 通常提供标记扫描。'],
            '为什么 Mapper 接口没有实现类也能调用？', 'MyBatis 为已注册接口创建代理，按方法对应的映射语句执行 SQL。',
            mybatisApi + 'Mapper.html'),
        annotation('@MapperScan', 'persistence', 'org.mybatis.spring.annotation.MapperScan',
            'MyBatis-Spring 注解，扫描指定包中的 Mapper 接口并注册代理 Bean。', ['类'],
            ['basePackages/value：Mapper 包名。', 'annotationClass、markerInterface：过滤条件。', 'sqlSessionFactoryRef：指定会话工厂 Bean。'],
            '@Configuration\n@MapperScan("com.example.mapper")\npublic class MyBatisConfig {}',
            ['包名是 Java 包 com.example.mapper，不是 XML 资源路径；来自 MyBatis-Spring 而非 MyBatis 核心。'],
            '已经 @MapperScan 后还要每个接口写 @Mapper 吗？', '默认扫描指定包中的接口时通常不必；若配置了注解过滤则要满足过滤条件。',
            'https://mybatis.org/spring/apidocs/org/mybatis/spring/annotation/MapperScan.html'),
        annotation('@Param', 'persistence', 'org.apache.ibatis.annotations.Param',
            '给 Mapper 方法参数指定稳定的 SQL 引用名称。', ['参数'], ['value：SQL 中使用的参数名。'],
            '@Select("SELECT id, name FROM users WHERE name = #{name} AND age >= #{age}")\nList<User> search(@Param("name") String keyword, @Param("age") int minAge);',
            ['SQL 引用名须与 value 一致；#{...} 绑定参数，而 ${...} 是文本拼接，不能随意替换。'],
            '多参数 Mapper 为什么常写 @Param？', '它显式固定 SQL 参数名，减少对默认命名或编译器参数名信息的依赖。',
            mybatisApi + 'Param.html'),
        annotation('@Select', 'persistence', 'org.apache.ibatis.annotations.Select',
            '直接在 Mapper 方法上声明查询 SQL。', ['方法'],
            ['value：SQL 字符串或字符串数组。', 'databaseId：数据库方言标识。', 'affectData：用于带数据修改效果的返回语句，MyBatis 3.5.12+。'],
            '@Select("SELECT id, name FROM users WHERE id = #{id}")\nUser findById(@Param("id") long id);',
            ['注解 SQL 也需要参数绑定和结果映射；复杂动态 SQL 可考虑 XML 或 Provider。'],
            '@Select 与 XML select 谁负责事务？', '它们都声明映射语句；事务由 SqlSession 或 Spring 事务管理机制控制。',
            mybatisApi + 'Select.html'),
        annotation('@Insert', 'persistence', 'org.apache.ibatis.annotations.Insert',
            '在 Mapper 方法上声明插入 SQL。', ['方法'], ['value：插入 SQL。', 'databaseId：数据库方言标识。'],
            '@Insert("INSERT INTO users(name) VALUES(#{name})")\nint insert(User user);',
            ['int 返回值通常表示影响行数，不是自增主键；主键回填可配合 @Options。'],
            'insert 返回的 int 是用户 id 吗？', '通常是影响行数。生成主键应通过主键回填配置读取。',
            mybatisApi + 'Insert.html'),
        annotation('@Update', 'persistence', 'org.apache.ibatis.annotations.Update',
            '在 Mapper 方法上声明更新 SQL。', ['方法'], ['value：更新 SQL。', 'databaseId：数据库方言标识。'],
            '@Update("UPDATE users SET name = #{name} WHERE id = #{id}")\nint rename(@Param("id") long id, @Param("name") String name);',
            ['注解不会自动补 WHERE 或实现乐观锁；要明确更新条件并检查影响行数。'],
            '@Update 会自动更新 Java 对象的所有字段吗？', '不会，只执行明确声明的 SQL。',
            mybatisApi + 'Update.html'),
        annotation('@Delete', 'persistence', 'org.apache.ibatis.annotations.Delete',
            '在 Mapper 方法上声明删除 SQL。', ['方法'], ['value：删除 SQL。', 'databaseId：数据库方言标识。'],
            '@Delete("DELETE FROM users WHERE id = #{id}")\nint deleteById(@Param("id") long id);',
            ['默认执行给定的物理删除 SQL；MyBatis 核心不会因这个注解自动启用逻辑删除。'],
            '@Delete 能自动将 deleted 字段置为 1 吗？', '不能。需要显式 UPDATE SQL 或另行设计；不要混淆 MyBatis-Plus 扩展。',
            mybatisApi + 'Delete.html'),
        annotation('@Options', 'persistence', 'org.apache.ibatis.annotations.Options',
            '给 Mapper 映射语句配置主键生成、缓存、超时和语句类型等执行选项。', ['方法'],
            ['useGeneratedKeys：使用 JDBC 生成主键。', 'keyProperty、keyColumn：回填属性与主键列。', 'timeout、fetchSize、useCache：执行选项。'],
            '@Insert("INSERT INTO users(name) VALUES(#{name})")\n@Options(useGeneratedKeys = true, keyProperty = "id", keyColumn = "id")\nint insert(User user);\n// 执行后从 user.getId() 读取回填的主键。',
            ['主键生成要数据库和 JDBC 驱动支持；User.id 要可写，@Param 包装对象时 keyProperty 也须对应路径。'],
            '开启 useGeneratedKeys 后主键在哪里？', '按 keyProperty 回填到参数对象中，方法的影响行数返回值并不变成主键。',
            mybatisApi + 'Options.html'),

        annotation('@Getter', 'lombok', 'lombok.Getter',
            '编译期生成字段 getter，类级使用通常覆盖非静态字段。', ['类', '字段'],
            ['value：访问级别，默认 PUBLIC。', 'lazy：对符合条件的字段启用惰性读取。'],
            '@Getter\npublic class UserView {\n    private String name;\n}',
            ['需要配置 Lombok 编译处理；它生成访问方法，不把可变对象自动变成不可变对象。'],
            '@Getter 是运行时通过反射调用字段吗？', '不是，Lombok 在编译阶段生成普通 getter 字节码。',
            lombokApi + 'lombok/Getter', 'high', '编译期'),
        annotation('@Setter', 'lombok', 'lombok.Setter',
            '编译期生成字段 setter，类级使用通常覆盖可写的非静态字段。', ['类', '字段'],
            ['value：访问级别，默认 PUBLIC。'],
            '@Setter\npublic class CreateUserRequest {\n    private String name;\n}',
            ['final 字段不会生成 setter；setter 不会自动执行 Bean Validation 约束检查。'],
            '类级 @Setter 会给 final 字段生成 setter 吗？', '不会，final 字段不通过 setter 修改。',
            lombokApi + 'lombok/Setter', 'high', '编译期'),
        annotation('@Data', 'lombok', 'lombok.Data',
            '组合生成 getter、非 final 字段 setter、toString、equals、hashCode 和必要参数构造器。', ['类'],
            ['staticConstructor：生成静态工厂名称，构造器转为 private。'],
            '@Data\npublic class UserDto {\n    private Long id;\n    private String name;\n}',
            ['生成 toString 时要注意敏感字段；可变字段参与 equals/hashCode 时，应谨慎把对象作为哈希键。', '已有显式构造器时 @Data 不再生成构造器。'],
            '@Data 是否只是 @Getter + @Setter？', '不止，还包含 toString、equals/hashCode 和必要参数构造器等行为。',
            lombokApi + 'lombok/Data', 'high', '编译期'),
        annotation('@Builder', 'lombok', 'lombok.Builder',
            '生成 Builder API，通过具名链式调用组装对象。', ['类', '构造器', '方法'],
            ['builderMethodName：入口方法名。', 'buildMethodName：构建方法名。', 'toBuilder：从已有对象生成 Builder。'],
            '@Builder\npublic class UserDto {\n    private Long id;\n    private String name;\n}\n// 使用：UserDto.builder().id(1L).name("Ada").build();',
            ['字段初始化值需要 @Builder.Default 才作为 Builder 默认值；与构造器注解组合时确认目标构造器存在。'],
            'Builder 会保证必填字段已经填写吗？', '通常不会自动保证；需构造器检查、校验或定制 Builder。',
            lombokApi + 'lombok/Builder', 'high', '编译期'),
        annotation('@RequiredArgsConstructor', 'lombok', 'lombok.RequiredArgsConstructor',
            '为未初始化的 final 字段和未初始化且标记 @NonNull 的字段生成构造器。', ['类'],
            ['access：访问级别。', 'staticName：可选静态工厂名称。'],
            '@Service\n@RequiredArgsConstructor\npublic class UserService {\n    private final UserMapper userMapper;\n    public User find(long id) { return userMapper.findById(id); }\n}',
            ['普通可变字段不会因为此注解成为构造器参数；已初始化 final 字段也不会进入参数列表。', 'Spring 注入仍要求依赖 Bean 存在；Lombok 只负责生成构造器。'],
            '它为什么适合 Spring 构造器注入？', '它为 final 依赖生成构造器；Spring 对只有一个构造器的 Bean 通常无需 @Autowired。',
            lombokApi + 'lombok/RequiredArgsConstructor', 'high', '编译期'),
        annotation('@NoArgsConstructor', 'lombok', 'lombok.NoArgsConstructor',
            '生成无参数构造器，适用于确实需要无参实例化的类型。', ['类'],
            ['access：访问级别。', 'force：强制为未初始化 final 字段赋默认值，默认 false。'],
            '@NoArgsConstructor\n@Getter @Setter\npublic class UserDto {\n    private Long id;\n    private String name;\n}',
            ['有未初始化 final 字段时默认无法生成；force=true 可能让对象以 null、0 等状态出现。'],
            '为什么不应随意对 final 依赖使用 force=true？', '它会绕过构造器所需状态，把字段置为默认值，容易破坏对象约束。',
            lombokApi + 'lombok/NoArgsConstructor', 'normal', '编译期'),
        annotation('@AllArgsConstructor', 'lombok', 'lombok.AllArgsConstructor',
            '为类的实例字段生成包含各字段参数的构造器，静态字段不参与。', ['类'],
            ['access：访问级别。', 'staticName：可选静态工厂名称。'],
            '@AllArgsConstructor\n@Getter\npublic class UserDto {\n    private Long id;\n    private String name;\n}',
            ['字段顺序变化会影响构造器参数顺序；全参数构造器不会自动满足序列化框架的无参要求。'],
            'AllArgsConstructor 与 RequiredArgsConstructor 区别？', '前者针对实例字段生成全参数构造器，后者只选择需要初始化的 final 与 @NonNull 字段。',
            lombokApi + 'lombok/AllArgsConstructor', 'normal', '编译期'),
        annotation('@Slf4j', 'lombok', 'lombok.extern.slf4j.Slf4j',
            '生成 SLF4J Logger 字段，默认名称 log。', ['类'], ['topic：自定义 Logger 名称。'],
            '@Slf4j\n@Service\npublic class UserService {\n    public void record(long id) { log.info("user id={}", id); }\n}',
            ['需要 SLF4J API 与合适日志实现；参数化日志可避免自行拼接，但仍不要记录敏感信息。'],
            '@Slf4j 与日志实现是什么关系？', '它只生成使用 SLF4J API 的日志字段，实际输出由日志实现负责。',
            lombokApi + 'lombok/extern/slf4j/Slf4j', 'high', '编译期'),

        annotation('@Transactional', 'advanced', 'org.springframework.transaction.annotation.Transactional',
            '声明事务边界与传播、隔离、回滚等规则，由事务基础设施拦截调用执行。', ['类', '方法'],
            ['propagation：默认 REQUIRED。', 'isolation：默认 DEFAULT。', 'rollbackFor、noRollbackFor：异常回滚规则。', 'readOnly：只读提示，默认 false。', 'transactionManager：指定事务管理器。'],
            '@Service\n@RequiredArgsConstructor\npublic class OrderService {\n    private final OrderMapper orders;\n    @Transactional(rollbackFor = Exception.class)\n    public void place(Order order) throws Exception {\n        orders.insert(order);\n        // 后续数据库操作与上述插入参加同一事务。\n    }\n}\n// 通过另一个 Bean 注入 OrderService 并调用 place。',
            ['默认代理模式下自调用不经过事务拦截；private 方法不能作为常规代理入口，类代理的 final 方法无法增强。', '标准默认规则对 RuntimeException 和 Error 回滚，受检异常需匹配回滚规则；捕获异常不再抛出会影响回滚判断。', 'readOnly 是给事务系统的提示，不保证阻止写 SQL；常规线程绑定事务不会自动传播到新线程。'],
            '为什么标了 @Transactional 仍没回滚？', '检查是否经过代理、事务管理器与数据源是否匹配、异常是否传播及是否命中回滚规则。',
            springSource('org.springframework.transaction.annotation.Transactional')),
        annotation('@EnableTransactionManagement', 'advanced', 'org.springframework.transaction.annotation.EnableTransactionManagement',
            '注册处理声明式事务所需的基础设施。', ['类'],
            ['mode：默认 PROXY。', 'proxyTargetClass：是否偏向类代理。', 'order：事务通知顺序。', 'rollbackOn：Spring 6.2+ 可调整默认回滚策略。'],
            '@Configuration\n@EnableTransactionManagement\npublic class TransactionConfig {\n    // 另行提供合适的 PlatformTransactionManager Bean。\n}',
            ['还需要事务管理器和对应资源；Boot 在条件满足时可自动启用，手动添加注解不是每个项目都必需。'],
            '只写 @Transactional 会自动创建事务管理器吗？', '不会，事务基础设施与资源管理器必须由配置或自动配置提供。',
            springSource('org.springframework.transaction.annotation.EnableTransactionManagement'), 'normal'),
        annotation('@Async', 'advanced', 'org.springframework.scheduling.annotation.Async',
            '把受代理的方法调用提交给任务执行器异步运行。', ['类', '方法'], ['value：执行器 Bean 名称或限定符。'],
            '// 配置类启用 @EnableAsync；由其他 Bean 调用此服务。\n@Service\npublic class ReportService {\n    @Async\n    public CompletableFuture<String> build() {\n        return CompletableFuture.completedFuture("ready");\n    }\n}',
            ['需要 @EnableAsync 或等效配置；默认代理模式下自调用不触发异步，private 或类代理 final 方法不适合作为入口。', '方法返回类型应是 void 或 Future 类型（可用 CompletableFuture）；不能直接返回普通 String。', 'void 方法异常需 AsyncUncaughtExceptionHandler 等机制处理；新线程不会自动继承调用者的常规事务。'],
            '@Async 方法返回 CompletableFuture 为什么还能异步？', '方法内部提供完成结果，代理返回代表异步任务执行状态的 Future。',
            springSource('org.springframework.scheduling.annotation.Async')),
        annotation('@EnableAsync', 'advanced', 'org.springframework.scheduling.annotation.EnableAsync',
            '启用按注解识别的异步方法执行支持。', ['类'],
            ['mode：默认 PROXY。', 'proxyTargetClass：类代理开关。', 'annotation：可定制异步标记注解。'],
            '@Configuration\n@EnableAsync\npublic class AsyncConfig {\n    // 可通过 Executor Bean 或 AsyncConfigurer 定制线程池。\n}',
            ['仅开启机制不代表线程池配置适合生产负载；需要考虑执行器容量和异常处理。'],
            '@EnableAsync 可以修复同类方法自调用吗？', '默认代理模式下不能；调用必须经过代理，或采用适合的其他增强方式。',
            springSource('org.springframework.scheduling.annotation.EnableAsync'), 'normal'),
        annotation('@Cacheable', 'advanced', 'org.springframework.cache.annotation.Cacheable',
            '按缓存名称和键查询缓存；命中时复用结果，未命中时调用方法并缓存结果。', ['类', '方法'],
            ['cacheNames/value：缓存名称。', 'key：缓存键 SpEL。', 'condition：执行前是否参与缓存。', 'unless：结果产生后是否否决缓存。', 'sync：协调同键并发加载。'],
            '// 配置类启用 @EnableCaching，并提供 CacheManager。\n@Service\n@RequiredArgsConstructor\npublic class UserService {\n    private final UserMapper users;\n    @Cacheable(cacheNames = "users", key = "#p0")\n    public User find(long id) { return users.findById(id); }\n}',
            ['需要 @EnableCaching 或等效配置及 CacheManager；默认代理模式下自调用不触发缓存。', '缓存一致性、淘汰和 TTL 需要额外设计；@Cacheable 本身不自动生成失效时间策略。'],
            '@Cacheable 的 condition 与 unless 区别？', 'condition 在调用前决定是否参与缓存，unless 在产生结果后决定是否缓存该结果。',
            springSource('org.springframework.cache.annotation.Cacheable')),
        annotation('@EnableCaching', 'advanced', 'org.springframework.cache.annotation.EnableCaching',
            '启用 Spring 注解式缓存拦截支持。', ['类'],
            ['mode：默认 PROXY。', 'proxyTargetClass：类代理开关。', 'order：缓存通知顺序。'],
            '@Configuration\n@EnableCaching\npublic class CacheConfig {\n    @Bean CacheManager cacheManager() {\n        return new ConcurrentMapCacheManager("users");\n    }\n}',
            ['仍需 CacheManager；示例是单进程内存缓存，多实例共享缓存需要其他实现。'],
            '只加 @Cacheable 为什么可能没缓存？', '先检查缓存是否启用、CacheManager 是否可用、调用是否经过代理。',
            'https://docs.spring.io/spring-framework/docs/6.2.14/javadoc-api/org/springframework/cache/annotation/EnableCaching.html', 'normal'),
        annotation('@Scheduled', 'advanced', 'org.springframework.scheduling.annotation.Scheduled',
            '让 Spring 调度器按间隔或 cron 调用方法。', ['方法'],
            ['fixedDelay：上次结束到下次开始的间隔。', 'fixedRate：按开始时间计算周期。', 'cron：六段表达式，首段是秒。', 'zone：cron 时区。', 'initialDelay：首次延迟。'],
            '// 配置类启用 @EnableScheduling。\n@Component\npublic class CleanupJob {\n    @Scheduled(cron = "0 0 2 * * *", zone = "Asia/Shanghai")\n    public void cleanup() { /* 清理过期数据 */ }\n}',
            ['常规定时方法应无参数，通常返回 void；普通返回值会被忽略。', '多实例应用通常每实例都会调度，注解本身不提供分布式互斥；cron 与系统五段表达式不同。'],
            'fixedDelay 与 fixedRate 有什么区别？', '前者从上次结束后计时，后者按计划开始时间计算周期，实际执行还受调度器与任务耗时影响。',
            springSource('org.springframework.scheduling.annotation.Scheduled')),
        annotation('@EnableScheduling', 'advanced', 'org.springframework.scheduling.annotation.EnableScheduling',
            '注册发现和调度 @Scheduled 方法的基础设施。', ['类'], ['无属性。'],
            '@Configuration\n@EnableScheduling\npublic class SchedulingConfig {}',
            ['要让任务对象由对应 Spring 容器管理；线程并发、阻塞和多实例协调需要单独配置。'],
            '@EnableScheduling 会创建分布式任务平台吗？', '不会，它启用当前应用上下文中的 Spring 调度机制。',
            springSource('org.springframework.scheduling.annotation.EnableScheduling'), 'normal')
    ];

    const find = name => annotations.find(item => item.name === name);
    find('@Repeatable').sources.push({
        label: 'Java 17 语言规范：重复注解与隐式容器',
        url: 'https://docs.oracle.com/javase/specs/jls/se17/html/jls-9.html#jls-9.7.5'
    });
    find('@Resource').sources.push({
        label: 'Spring 6.2：@Resource 注入规则',
        url: 'https://docs.spring.io/spring-framework/reference/6.2/core/beans/annotation-config/resource.html'
    });
    find('@Validated').sources.push({
        label: 'Spring 6.2：MVC 校验与 6.1 起的内置方法校验',
        url: 'https://docs.spring.io/spring-framework/reference/6.2/web/webmvc/mvc-controller/ann-validation.html'
    });
    find('@ConfigurationProperties').sources.push({
        label: 'Spring Boot 3.5：构造器绑定与 record',
        url: 'https://docs.spring.io/spring-boot/3.5/reference/features/external-config.html#features.external-config.typesafe-configuration-properties.constructor-binding'
    });
    find('@Transactional').sources.push({
        label: 'Spring 6.2：事务代理与自调用',
        url: 'https://docs.spring.io/spring-framework/reference/6.2/data-access/transaction/declarative/annotations.html'
    });

    const basics = [
        { id: 'metadata', title: '注解是元数据，谁读取它才决定行为',
            body: '注解给程序元素附加结构化信息。@Override 由编译器检查，Lombok 在编译阶段生成代码，Spring、MyBatis 和校验实现主要在框架运行阶段处理。只写一个注解，并不会天然获得对应业务能力。先问：谁读取它、何时读取、需要什么配置？' },
        { id: 'retention', title: '三种保留策略：默认是 CLASS',
            body: 'SOURCE 只留在源码，编译后丢弃；CLASS 保留在 class 文件中，但通常不能被常规运行时反射读取；RUNTIME 保留到运行时，可通过反射读取。不写 @Retention 时默认 CLASS。注解自身的保留策略与处理它的实际阶段要区分，例如 @Deprecated 保留到运行时，但常见用途是编译器警告。',
            example: '@Retention(RetentionPolicy.RUNTIME)\n@Target(ElementType.METHOD)\npublic @interface Audit { String value() default ""; }' },
        { id: 'custom', title: '自定义注解与反射读取',
            body: '用 @interface 定义注解。属性可用基本类型、String、Class、枚举、其他注解及这些类型的一维数组，不能随意用 List、普通对象或 null 默认值。可通过 default 提供默认值。RUNTIME 注解可用 getAnnotation 等读取，但还需自行编写处理逻辑或接入框架机制。',
            example: '@Retention(RetentionPolicy.RUNTIME)\n@Target(ElementType.METHOD)\n@interface Audit { String action(); }\nclass Demo { @Audit(action = "create") public void create() {} }\n// Method m = Demo.class.getMethod("create");\n// Audit a = m.getAnnotation(Audit.class);\n// System.out.println(a.action());' },
        { id: 'inheritance', title: '@Inherited 只沿类的父类链',
            body: '@Inherited 影响查询类注解时的父类搜索，不覆盖接口、方法和字段。Spring 等框架可能采用组合注解和额外层级搜索，因此不能把框架查找规则完全等同于 Java 原生反射规则。' },
        { id: 'spring-lifecycle', title: 'Spring 注解要进入扫描、注册与代理流程',
            body: '组件先进入容器，依赖注入才有处理机会。事务、异步、缓存通常还需要相应基础设施与代理；默认代理模式下，对象内部 this.method() 自调用会绕过代理。类代理不能增强 final 方法，private 方法也不适合作为常规代理入口。先检查对象由谁创建，以及调用是否通过容器提供的代理。' },
        { id: 'versions', title: '先看完整包名，再看版本',
            body: '本专区主要按 Java 17、Spring Framework 6.2 与 Spring Boot 3 解释；Boot 3 中校验与资源注入使用 jakarta.validation、jakarta.annotation，Boot 2 常见 javax 对应包。MyBatis 与 MyBatis-Spring 是相关但不同模块，MyBatis-Plus 的扩展注解不能当作 MyBatis 核心能力。Lombok 注解需要编译处理配置。' },
        { id: 'learning-path', title: '建议学习顺序与示例阅读方式',
            body: '先学元注解与 JDK，再按 Spring 容器 → Boot 配置 → Web 参数绑定 → 校验 → MyBatis → Lombok → 事务、异步、缓存与调度推进。先看一句话作用，再读示例和易错点，最后口述面试题答案。示例为教学片段，省略了 import、依赖配置和无关类型定义；各条完整包名用于确定正确导入。' }
    ];

    return { categories, annotations, basics };
}));
