(function () {
 const KEYS=['resume-prep-mastery','resume-prep-checklist','resume-prep-drafts'],PAGE_SIZE=20;
 const TABS=[['questions','面试问答'],['pitches','介绍稿'],['stories','简历脉络'],['sources','资料']];
 const SOURCES=[['all','全部'],['resume','整体介绍'],['zhishu','知枢'],['beiruan','北软'],['yonyou','用友'],['skills','技术基础']];
 const data=()=>window.RESUME_PREP_DATA;
 const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
 const sourceName=id=>SOURCES.find(([k])=>k===id)?.[1]||'全部';
 const obj=v=>v&&typeof v==='object'&&!Array.isArray(v);
 function load(k){try{const v=JSON.parse(localStorage.getItem(k)||'{}');return obj(v)?v:{};}catch(_){return {};}}
 const cleanDrafts=v=>Object.fromEntries(data().questions.filter(q=>typeof v[q.id]==='string'&&v[q.id]).map(q=>[q.id,v[q.id].slice(0,6000)]));
 const state={tab:'questions',source:'all',search:'',level:'all',topic:'all',priority:'all',page:1,visible:true,toggled:new Set(),mockId:null,mastery:load(KEYS[0]),checklist:load(KEYS[1]),drafts:cleanDrafts(load(KEYS[2]))};
 function persist(){try{[state.mastery,state.checklist,state.drafts].forEach((v,i)=>localStorage.setItem(KEYS[i],JSON.stringify(v)));}catch(_){if(typeof toast==='function')toast('未保存到本机，请检查存储空间');return;}if(typeof scheduleCloudSync==='function')scheduleCloudSync();}
 const revealed=id=>state.visible?!state.toggled.has(id):state.toggled.has(id);
 const topics=()=>[...new Set(data().questions.filter(q=>state.source==='all'||q.source===state.source).map(q=>q.topic).filter(Boolean))];
 function filtered(){const term=state.search.trim().toLowerCase();return data().questions.filter(q=>{
  const level=state.mastery[q.id]||'new';
  return (state.source==='all'||q.source===state.source)&&(state.topic==='all'||q.topic===state.topic)&&(state.priority==='all'||(q.priority||'must')===state.priority)&&(state.level==='all'||(state.level==='weak'?['hard','fuzzy'].includes(level):level===state.level))&&(!term||`${q.question} ${q.answer} ${q.followup} ${q.followupAnswer||''} ${q.topic||''} ${sourceName(q.source)}`.toLowerCase().includes(term));
 });}
 function pageData(){const qs=filtered(),pages=Math.max(1,Math.ceil(qs.length/PAGE_SIZE));state.page=Math.max(1,Math.min(state.page,pages));return {qs,pages,items:qs.slice((state.page-1)*PAGE_SIZE,state.page*PAGE_SIZE)};}
 function tabs(){return `<nav class="resume-reading-tabs" aria-label="简历准备模块导航">${TABS.map(([id,label])=>`<button class="${state.tab===id?'active':''}" aria-current="${state.tab===id?'page':'false'}" data-resume-tab="${id}" onclick="setResumePrepTab('${id}')">${label}</button>`).join('')}</nav>`;}
 function sources(allowed=SOURCES.map(([id])=>id)){return `<div class="resume-reading-sources" aria-label="按经历筛选">${SOURCES.filter(([id])=>allowed.includes(id)).map(([id,label])=>`<button aria-pressed="${state.source===id}" class="${state.source===id?'active':''}" data-resume-source="${id}" onclick="setResumePrepSource('${id}')">${label}${state.tab==='questions'?` <small>${id==='all'?data().questions.length:data().questions.filter(q=>q.source===id).length}</small>`:''}</button>`).join('')}</div>`;}
 function cards(qs){if(!qs.length)return `<div class="career-empty"><h3>没有匹配的问题</h3><p>${state.level==='weak'?'标记为待复习的问题会出现在这里。':'换个关键词，或清空筛选。'}</p><button class="career-secondary" onclick="resetResumeFilters()">清空筛选</button></div>`;
  return qs.map(q=>{const open=revealed(q.id),marked=['hard','fuzzy'].includes(state.mastery[q.id]),priority=q.priority||'must';return `<article class="resume-qa-card${open?' revealed':''}${state.mockId===q.id?' mock-focus':''}" id="resume-${q.id}" data-priority="${priority}">
   <button class="resume-question" aria-expanded="${open}" aria-controls="answer-${q.id}" onclick="toggleResumeAnswer('${q.id}')"><span class="resume-q-mark">Q</span><span><small>${sourceName(q.source)} · ${esc(q.topic||'经历深挖')} <em>${priority==='must'?'必会':'深入'}</em></small>${esc(q.question)}</span><i>${open?'收起':'看答案'}</i></button>
   <div class="resume-answer" id="answer-${q.id}"><p class="resume-direct-answer">${esc(q.answer)}</p><div class="resume-followup"><strong>继续追问</strong><p class="resume-followup-question">${esc(q.followup)}</p>${q.followupAnswer?`<p>${esc(q.followupAnswer)}</p>`:''}</div></div>
   <footer class="resume-reading-card-footer"><button aria-pressed="${marked}" class="${marked?'active':''}" onclick="toggleResumeReview('${q.id}')">${marked?'★ 已标记':'☆ 待复习'}</button></footer></article>`;}).join('');
 }
 function pagination(pos){const {qs,pages}=pageData();return `<div class="resume-reading-pagination" id="resume-pagination-${pos}"><span role="status">${qs.length?`${(state.page-1)*PAGE_SIZE+1}–${Math.min(state.page*PAGE_SIZE,qs.length)}`:'0'} / ${qs.length} 道</span><div><button aria-label="上一页" ${state.page===1?'disabled':''} onclick="setResumeReadingPage(${state.page-1})">←</button><span>${state.page} / ${pages}</span><button aria-label="下一页" ${state.page===pages?'disabled':''} onclick="setResumeReadingPage(${state.page+1})">→</button></div></div>`;}
 function questions(){const page=pageData();return `${sources()}<div class="resume-reading-filters"><label class="career-search"><input type="search" aria-label="搜索简历问题" value="${esc(state.search)}" placeholder="搜索问题、技术词或答案" oninput="filterResumeQuestions(this.value)"></label><select id="resumeTopicFilter" aria-label="按主题筛选" onchange="setResumeTopic(this.value)"><option value="all">全部主题</option>${topics().map(t=>`<option value="${esc(t)}" ${state.topic===t?'selected':''}>${esc(t)}</option>`).join('')}</select><select id="resumePriorityFilter" aria-label="按深度筛选" onchange="setResumePriority(this.value)">${[['all','全部问题'],['must','必会'],['deep','深入追问']].map(([id,label])=>`<option value="${id}" ${state.priority===id?'selected':''}>${label}</option>`).join('')}</select></div>
  <div class="resume-reading-tools"><div><button id="resumeRevealAll" onclick="toggleResumeAllAnswers()">${state.visible?'遮住答案':'展开答案'}</button><button id="resumeWeakFilter" aria-pressed="${state.level==='weak'}" onclick="toggleResumeWeak()">${state.level==='weak'?'查看全部':'只看待复习'}</button><button onclick="resetResumeFilters()">清空筛选</button></div><button id="resumeRandom" onclick="randomResumeQuestion()" ${page.qs.length?'':'disabled'}>抽一道 →</button></div>${pagination('top')}<section class="resume-question-list" id="resume-question-results">${cards(page.items)}</section>${pagination('bottom')}`;}
 function pitches(){return `${sources(['all','resume','zhishu','beiruan','yonyou'])}<section class="resume-reading-pitches">${data().pitches.filter(p=>state.source==='all'||p.source===state.source).map(p=>`<article><header><div><small>${sourceName(p.source)} · ${esc(p.duration)}</small><h2>${esc(p.title)}</h2></div><button class="career-text" onclick="copyResumePitch('${p.id}')">复制</button></header><p>${esc(p.content)}</p></article>`).join('')}</section>`;}
 function stories(){return `${sources(['all','zhishu','beiruan','yonyou'])}<section class="resume-reading-claims">${window.RESUME_CLAIMS.items.filter(c=>state.source==='all'||c.source===state.source).map(c=>`<article><header><small>${sourceName(c.source)}</small><h2>${esc(c.title)}</h2></header><blockquote>${esc(c.quote)}</blockquote><div>${c.questionIds.map(id=>{const q=data().questions.find(q=>q.id===id);return q?`<button onclick="practiceResumeQuestion('${id}')">${esc(q.question)} <span>→</span></button>`:'';}).join('')}</div><button class="career-text" onclick="practiceResumeSource('${c.source}')">查看${sourceName(c.source)}全部问答 →</button></article>`).join('')}</section>`;}
 function files(){const refs=[...new Map((data().references||[]).filter(r=>/^https:\/\//.test(r.url)).map(r=>[r.url,r])).values()];return `<section class="resume-reading-files">${data().sources.filter(s=>s.file).map(s=>`<a href="${esc(s.file)}" target="_blank" rel="noopener"><div><strong>${esc(s.name)}</strong><small>${s.id==='resume'?`当前简历 · ${window.RESUME_CLAIMS.date}`:'补充手册'}</small></div><span>${s.id==='resume'?'查看 PDF':'下载 DOCX'} ↗</span></a>`).join('')}</section>${refs.length?`<details class="resume-reading-references"><summary>技术参考 · 官方文档</summary>${refs.map(r=>`<a href="${esc(r.url)}" target="_blank" rel="noopener">${esc(r.label)} ↗</a>`).join('')}</details>`:''}`;}
 window.renderResumePrep=()=>`<div class="resume-prep resume-reading">${tabs()}<div class="resume-view">${({questions,pitches,stories,sources:files}[state.tab]||questions)()}</div></div>`;
 window.renderResumePrepTOC=()=>TABS.map(([id,label])=>`<li><button class="toc-item" onclick="setResumePrepTab('${id}')">${label}</button></li>`).join('');
 window.setResumePrepTab=tab=>{state.tab=TABS.some(([id])=>id===tab)?tab:'questions';state.mockId=null;if((state.tab==='stories'&&['resume','skills'].includes(state.source))||(state.tab==='pitches'&&state.source==='skills'))state.source='all';renderAll();document.querySelector('[data-resume-tab="'+state.tab+'"]')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'smooth'});};
 window.setResumePrepSource=source=>{state.source=SOURCES.some(([id])=>id===source)?source:'all';state.mockId=null;state.page=1;if(!topics().includes(state.topic))state.topic='all';renderAll();document.querySelector('[data-resume-source="'+state.source+'"]')?.focus({preventScroll:true});};
 window.openResumeSource=source=>{state.source=source;state.topic='all';state.priority='all';state.search='';state.level='all';state.page=1;window.setResumePrepTab('questions');};
 function updateResults(){const {items,qs}=pageData(),list=document.getElementById('resume-question-results');if(list)list.innerHTML=cards(items);for(const pos of ['top','bottom']){const el=document.getElementById(`resume-pagination-${pos}`);if(el)el.outerHTML=pagination(pos);}const random=document.getElementById('resumeRandom');if(random)random.disabled=!qs.length;}
 window.filterResumeQuestions=v=>{state.search=String(v||'');state.page=1;state.mockId=null;updateResults();};
 window.setResumeTopic=v=>{state.topic=topics().includes(v)?v:'all';state.page=1;state.mockId=null;updateResults();};
 window.setResumePriority=v=>{state.priority=['must','deep'].includes(v)?v:'all';state.page=1;state.mockId=null;updateResults();};
 window.setResumePrepMastery=v=>{state.level=['all','new','weak','known'].includes(v)?v:'all';state.page=1;state.mockId=null;renderAll();};
 window.resetResumeFilters=()=>{state.source='all';state.search='';state.level='all';state.topic='all';state.priority='all';state.page=1;state.mockId=null;renderAll();};
 window.setResumeReadingPage=p=>{state.page=Number.isFinite(p)?Math.trunc(p):1;state.mockId=null;renderAll();document.querySelector('.resume-question')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'smooth'});};
 window.toggleResumeAllAnswers=()=>{state.visible=!state.visible;state.toggled.clear();updateResults();const button=document.getElementById('resumeRevealAll');if(button)button.textContent=state.visible?'遮住答案':'展开答案';};
 window.toggleResumeAnswer=id=>{if(!data().questions.some(q=>q.id===id))return;if(state.toggled.has(id))state.toggled.delete(id);else state.toggled.add(id);const card=document.getElementById(`resume-${id}`);if(card){const open=revealed(id);card.classList.toggle('revealed',open);card.querySelector('.resume-question')?.setAttribute('aria-expanded',String(open));const indicator=card.querySelector('.resume-question i');if(indicator)indicator.textContent=open?'收起':'看答案';}};
 function focusQuestion(id){requestAnimationFrame(()=>{const card=document.getElementById(`resume-${id}`);card?.querySelector('.resume-question')?.focus({preventScroll:true});card?.scrollIntoView({behavior:'smooth',block:'start'});});}
 window.practiceResumeQuestion=id=>{const q=data().questions.find(q=>q.id===id);if(!q)return;state.tab='questions';state.source=q.source;state.search='';state.level='all';state.topic='all';state.priority='all';state.mockId=id;if(state.visible)state.toggled.delete(id);else state.toggled.add(id);state.page=Math.floor(filtered().findIndex(q=>q.id===id)/PAGE_SIZE)+1;renderAll();focusQuestion(id);};
 window.randomResumeQuestion=()=>{const pool=filtered();if(!pool.length)return;const weak=pool.filter(q=>state.mastery[q.id]!=='known'),preferred=weak.length?weak:pool,others=preferred.filter(q=>q.id!==state.mockId),choices=others.length?others:preferred,q=choices[Math.floor(Math.random()*choices.length)];state.tab='questions';state.mockId=q.id;if(state.visible)state.toggled.add(q.id);else state.toggled.delete(q.id);state.page=Math.floor(pool.findIndex(v=>v.id===q.id)/PAGE_SIZE)+1;renderAll();focusQuestion(q.id);};
 window.startResumePractice=()=>{state.tab='questions';state.source='all';state.search='';state.level='all';state.topic='all';state.priority='all';window.randomResumeQuestion();};
 window.reviewResumeWeak=()=>{state.tab='questions';state.source='all';state.search='';state.topic='all';state.priority='all';state.level='weak';state.page=1;state.mockId=null;renderAll();};
 window.toggleResumeWeak=()=>{state.level=state.level==='weak'?'all':'weak';state.page=1;state.mockId=null;renderAll();document.getElementById('resumeWeakFilter')?.focus({preventScroll:true});};
 window.practiceResumeSource=window.openResumeSource;
 window.rateResumeQuestion=(id,level)=>{if(!data().questions.some(q=>q.id===id)||!['known','fuzzy','hard'].includes(level))return;state.mastery[id]=level;persist();updateResults();};
 window.toggleResumeReview=id=>{if(!data().questions.some(q=>q.id===id))return;if(['hard','fuzzy'].includes(state.mastery[id]))delete state.mastery[id];else state.mastery[id]='hard';persist();updateResults();const target=document.querySelector(`#resume-${id} .resume-reading-card-footer button`)||document.getElementById('resumeWeakFilter');target?.focus({preventScroll:true});};
 // Preserve saved personal answers through complete backups without restoring retired editors.
 window.saveResumeDraft=(id,v)=>{if(!data().questions.some(q=>q.id===id)||typeof v!=='string')return;if(v)state.drafts[id]=v.slice(0,6000);else delete state.drafts[id];persist();};
 window.copyResumePitch=async id=>{const p=data().pitches.find(p=>p.id===id);if(!p)return;try{await navigator.clipboard.writeText(p.content);if(typeof toast==='function')toast('介绍稿已复制');}catch(_){if(typeof toast==='function')toast('复制失败，请选择文字复制');}};
 window.getResumePrepSnapshot=()=>({mastery:state.mastery,checklist:state.checklist,drafts:state.drafts,workbench:ResumeWorkbench.getSnapshot()});
 window.applyResumePrepSnapshot=s=>{if(!obj(s))return;state.mastery=obj(s.mastery)?s.mastery:{};state.checklist=obj(s.checklist)?s.checklist:{};if(obj(s.drafts))state.drafts=cleanDrafts(s.drafts);ResumeWorkbench.applySnapshot(s.workbench);[state.mastery,state.checklist,state.drafts].forEach((v,i)=>localStorage.setItem(KEYS[i],JSON.stringify(v)));};
})();
