"""Build standalone reading data from the checked-in Markdown references."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def sections(text, level):
    result = []
    current = None
    fence = False
    for line in text.splitlines():
        if line.startswith('```'):
            fence = not fence
        match = not fence and re.match(r'^' + '#' * level + r' (\d+(?:\.\d+)?)\.?(?:\s+)(.+)$', line)
        if match:
            current = {'id': match[1], 'title': match[2], 'lines': []}
            result.append(current)
        elif current:
            current['lines'].append(line)
    return result


def clean(text):
    text = re.sub(r'<a id="[^"]+"></a>\s*', '', text)
    text = re.sub(r'^\[S\d+\]:.*$', '', text, flags=re.M)
    text = text.replace('**【校正】**', '').replace('【校正】', '').replace('【补充】', '')
    return text.strip().strip('-').strip()


def main():
    source = ROOT / 'assets/guides'
    full = (source / 'java-backend-commands.md').read_text(encoding='utf-8-sig')
    core = (source / 'core-40.md').read_text(encoding='utf-8-sig')
    commands = []
    for line in core.splitlines():
        if not re.match(r'^\| \d{2} \|', line):
            continue
        number, environment, command, purpose = [cell.strip() for cell in re.split(r'(?<!\\)\|', line)[1:-1]]
        commands.append(dict(id=number, environment=environment, command=command.strip('`'), purpose=purpose))
    chapters, scenarios = [], []
    for section in sections(full, 2):
        number = int(section['id'])
        content = clean('\n'.join(section['lines']))
        if number == 21:
            for scene in sections(content, 3):
                scenarios.append(dict(id='scene-' + scene['id'].replace('.', '-'), title=clean(scene['title']), content=clean('\n'.join(scene['lines']))))
        elif number != 22:
            title = clean(section['title'])
            if number == 28:
                title = '参考文档'
                content = content.split('### 28.2 官方文档与上游手册', 1)[1].split('### 28.3', 1)[0].strip()
            chapters.append(dict(id=f'c{number:02}', title=title, content=content))
    assert len(commands) == 40 and len(chapters) == 27 and len(scenarios) == 14
    result = dict(core=commands, chapters=chapters, scenarios=scenarios)
    (ROOT / 'data/command-guide.js').write_text('// Generated by scripts/import-command-guide.py; reading material only.\nwindow.COMMAND_GUIDE_DATA = ' + json.dumps(result, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
    print(f'Guide: {len(commands)} core commands, {len(chapters)} chapters, {len(scenarios)} scenarios')


if __name__ == '__main__':
    main()
